# Shakespear's Sonnets

추준호(20224224)

In [206]:
import re

In [207]:
corpus = []

In [208]:
with open('sonnets.txt','r') as f:
    sonnet = ''
    
    for line in f.readlines():
        if re.match(r'\d+', line):
            if sonnet:
                corpus.append(sonnet)          
                
            sonnet = ''
            
        else :
            sonnet += line
        
    corpus.append(sonnet)

In [209]:
len(corpus)

154

In [210]:
print(corpus[0])


From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But, as the riper should by time decease,
His tender heir might bear his memory.
But thou, contracted to thine own bright eyes,
Feed'st thy light's flame with self-substantial fuel,
Making a famine where abundance lies,
Thyself thy foe, to thy sweet self too cruel.
Thou that art now the world's fresh ornament
And only herald to the gaudy spring
Within thine own bud buriest thy content
And, tender churl, mak'st waste in niggarding.
  Pity the world, or else this glutton be--
  To eat the world's due, by the grave and thee.




In [211]:
corpus = [x.strip() for x in corpus]

In [212]:
corpus[0]

"From fairest creatures we desire increase,\nThat thereby beauty's rose might never die,\nBut, as the riper should by time decease,\nHis tender heir might bear his memory.\nBut thou, contracted to thine own bright eyes,\nFeed'st thy light's flame with self-substantial fuel,\nMaking a famine where abundance lies,\nThyself thy foe, to thy sweet self too cruel.\nThou that art now the world's fresh ornament\nAnd only herald to the gaudy spring\nWithin thine own bud buriest thy content\nAnd, tender churl, mak'st waste in niggarding.\n  Pity the world, or else this glutton be--\n  To eat the world's due, by the grave and thee."

In [213]:
for idx, sonnet in enumerate(corpus[:3]):
    print(f'Soonet #{idx + 1}')
    print(sonnet)
    print()

Soonet #1
From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But, as the riper should by time decease,
His tender heir might bear his memory.
But thou, contracted to thine own bright eyes,
Feed'st thy light's flame with self-substantial fuel,
Making a famine where abundance lies,
Thyself thy foe, to thy sweet self too cruel.
Thou that art now the world's fresh ornament
And only herald to the gaudy spring
Within thine own bud buriest thy content
And, tender churl, mak'st waste in niggarding.
  Pity the world, or else this glutton be--
  To eat the world's due, by the grave and thee.

Soonet #2
When forty winters shall besiege thy brow
And dig deep trenches in thy beauty's field,
Thy youth's proud livery, so gazed on now,
Will be a tattered weed of small worth held.
Then being asked where all thy beauty lies,
Where all the treasure of thy lusty days,
To say within thine own deep-sunken eyes
Were an all-eating shame and thriftless praise.
How much more 

# Tokenize

In [214]:
import nltk
import string

In [215]:
from nltk.corpus import stopwords

In [218]:
#nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /Users/kakao/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [219]:
def tokenize(text):
    text = text.lower()
    stemmer = nltk.stem.SnowballStemmer('english')
    
    for token in nltk.word_tokenize(text):
        if token in string.punctuation:
            continue
        elif token in stopwords.words('english'):
            continue
            
        yield stemmer.stem(token)

In [220]:
for doc in corpus[:2]:
    
    token = list(tokenize(doc))
    
    print(doc)
    print(token)
    print()

From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But, as the riper should by time decease,
His tender heir might bear his memory.
But thou, contracted to thine own bright eyes,
Feed'st thy light's flame with self-substantial fuel,
Making a famine where abundance lies,
Thyself thy foe, to thy sweet self too cruel.
Thou that art now the world's fresh ornament
And only herald to the gaudy spring
Within thine own bud buriest thy content
And, tender churl, mak'st waste in niggarding.
  Pity the world, or else this glutton be--
  To eat the world's due, by the grave and thee.
['fairest', 'creatur', 'desir', 'increas', 'therebi', 'beauti', "'s", 'rose', 'might', 'never', 'die', 'riper', 'time', 'deceas', 'tender', 'heir', 'might', 'bear', 'memori', 'thou', 'contract', 'thine', 'bright', 'eye', "feed'st", 'thi', 'light', "'s", 'flame', 'self-substanti', 'fuel', 'make', 'famin', 'abund', 'lie', 'thyself', 'thi', 'foe', 'thi', 'sweet', 'self', 'cruel', 'thou

# Gensim

## (1) Bag of words

In [221]:
import gensim

In [222]:
tokenized_corpus = [list(tokenize(x)) for x in corpus]

In [223]:
lexicon = gensim.corpora.Dictionary(tokenized_corpus)

In [224]:
len(lexicon)

2339

In [225]:
for x in lexicon.items():
    print(x)

(0, "'s")
(1, '--')
(2, 'abund')
(3, 'art')
(4, 'bear')
(5, 'beauti')
(6, 'bright')
(7, 'bud')
(8, 'buriest')
(9, 'churl')
(10, 'content')
(11, 'contract')
(12, 'creatur')
(13, 'cruel')
(14, 'deceas')
(15, 'desir')
(16, 'die')
(17, 'due')
(18, 'eat')
(19, 'els')
(20, 'eye')
(21, 'fairest')
(22, 'famin')
(23, "feed'st")
(24, 'flame')
(25, 'foe')
(26, 'fresh')
(27, 'fuel')
(28, 'gaudi')
(29, 'glutton')
(30, 'grave')
(31, 'heir')
(32, 'herald')
(33, 'increas')
(34, 'lie')
(35, 'light')
(36, "mak'st")
(37, 'make')
(38, 'memori')
(39, 'might')
(40, 'never')
(41, 'niggard')
(42, 'ornament')
(43, 'piti')
(44, 'riper')
(45, 'rose')
(46, 'self')
(47, 'self-substanti')
(48, 'spring')
(49, 'sweet')
(50, 'tender')
(51, 'thee')
(52, 'therebi')
(53, 'thi')
(54, 'thine')
(55, 'thou')
(56, 'thyself')
(57, 'time')
(58, 'wast')
(59, 'within')
(60, 'world')
(61, "''")
(62, '``')
(63, 'all-eat')
(64, 'answer')
(65, 'ask')
(66, 'besieg')
(67, 'blood')
(68, 'brow')
(69, 'child')
(70, 'cold')
(71, 'couldst')

In [226]:
for toekns in tokenized_corpus[:3]:
    vec = lexicon.doc2bow(tokens)
    
    print(vec)
    print()

[(0, 2), (15, 1), (21, 1), (34, 1), (94, 1), (107, 1), (130, 3), (231, 2), (303, 2), (325, 1), (344, 1), (346, 1), (361, 1), (439, 1), (440, 2), (525, 1), (526, 1), (554, 1), (608, 1), (664, 1), (668, 1), (787, 1), (981, 1), (1134, 1), (1158, 2), (1162, 3), (1164, 1), (1200, 2), (1247, 1), (1334, 1), (1426, 1), (1730, 1), (1749, 1), (1931, 2), (2015, 1), (2087, 1), (2093, 1), (2170, 2), (2314, 1), (2315, 1), (2328, 1), (2329, 2), (2330, 1), (2331, 1), (2332, 1), (2333, 1), (2334, 1), (2335, 1), (2336, 1), (2337, 1), (2338, 1)]

[(0, 2), (15, 1), (21, 1), (34, 1), (94, 1), (107, 1), (130, 3), (231, 2), (303, 2), (325, 1), (344, 1), (346, 1), (361, 1), (439, 1), (440, 2), (525, 1), (526, 1), (554, 1), (608, 1), (664, 1), (668, 1), (787, 1), (981, 1), (1134, 1), (1158, 2), (1162, 3), (1164, 1), (1200, 2), (1247, 1), (1334, 1), (1426, 1), (1730, 1), (1749, 1), (1931, 2), (2015, 1), (2087, 1), (2093, 1), (2170, 2), (2314, 1), (2315, 1), (2328, 1), (2329, 2), (2330, 1), (2331, 1), (2332, 1),

In [227]:
for raw, toekns in zip(corpus[:3], tokenized_corpus[:3]):
    vec = lexicon.doc2bow(tokens)
    
    print(raw)
    print(vec)
    print()

From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But, as the riper should by time decease,
His tender heir might bear his memory.
But thou, contracted to thine own bright eyes,
Feed'st thy light's flame with self-substantial fuel,
Making a famine where abundance lies,
Thyself thy foe, to thy sweet self too cruel.
Thou that art now the world's fresh ornament
And only herald to the gaudy spring
Within thine own bud buriest thy content
And, tender churl, mak'st waste in niggarding.
  Pity the world, or else this glutton be--
  To eat the world's due, by the grave and thee.
[(0, 2), (15, 1), (21, 1), (34, 1), (94, 1), (107, 1), (130, 3), (231, 2), (303, 2), (325, 1), (344, 1), (346, 1), (361, 1), (439, 1), (440, 2), (525, 1), (526, 1), (554, 1), (608, 1), (664, 1), (668, 1), (787, 1), (981, 1), (1134, 1), (1158, 2), (1162, 3), (1164, 1), (1200, 2), (1247, 1), (1334, 1), (1426, 1), (1730, 1), (1749, 1), (1931, 2), (2015, 1), (2087, 1), (2093, 1), (2170,

## (2) tf-idf

In [228]:
tfidf = gensim.models.TfidfModel(dictionary = lexicon , normalize=True)

In [229]:
for raw, toekns in zip(corpus[:3], tokenized_corpus[:3]):
    vec = lexicon.doc2bow(tokens)
    vec = tfidf[vec]
    
    print(raw)
    print(vec)
    print()

From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But, as the riper should by time decease,
His tender heir might bear his memory.
But thou, contracted to thine own bright eyes,
Feed'st thy light's flame with self-substantial fuel,
Making a famine where abundance lies,
Thyself thy foe, to thy sweet self too cruel.
Thou that art now the world's fresh ornament
And only herald to the gaudy spring
Within thine own bud buriest thy content
And, tender churl, mak'st waste in niggarding.
  Pity the world, or else this glutton be--
  To eat the world's due, by the grave and thee.
[(0, 0.027386775494956658), (15, 0.07323031331493926), (21, 0.10814664073019317), (34, 0.05632856416427394), (94, 0.06359004104094827), (107, 0.1286803456553076), (130, 0.04200112094301088), (231, 0.12397672095219288), (303, 0.16200511859511485), (325, 0.047486045401847386), (344, 0.07560148842301351), (346, 0.06528329470581776), (361, 0.05902350068364393), (439, 0.06899111191549218

## Clustering

In [230]:
from gensim.matutils import sparse2full

In [231]:
vectors = []

In [232]:
for tokens in tokenized_corpus:
    vec = lexicon.doc2bow(tokens)
    vec = [(x[0], 1) for x in vec]
    vec = tfidf[vec]
    
    vec = sparse2full(vec, len(lexicon))
    
    vectors.append(vec)

In [233]:
vectors[0]

array([0.01795831, 0.1149007 , 0.13316056, ..., 0.        , 0.        ,
       0.        ], dtype=float32)

In [234]:
vectors[0].shape

(2339,)

In [235]:
distance = nltk.cluster.cosine_distance

In [236]:
kmeans = nltk.cluster.KMeansClusterer(
    num_means = 6,
    distance = distance,
    avoid_empty_clusters = True,
)

In [237]:
kmeans.cluster(vectors)

In [238]:
kmeans.classify(vectors[88])

3

In [239]:
from collections import defaultdict

In [240]:
temp = {
    'a' : 10
}

In [241]:
temp['a']

10

In [242]:
#temp['b']

In [243]:
temp = defaultdict(int)
temp['a'] = 10

In [244]:
temp['b']

0

In [245]:
classified = defaultdict(list)

In [246]:
for i in range(len(corpus)):
    no = i + 1
    sonnet = corpus[i]
    vec = vectors[i]
    
    group = kmeans.classify(vec)
    entry = (no, sonnet, vec)
    
    classified[group].append(entry)

In [247]:
classified[0]

[(2,
  'When forty winters shall besiege thy brow\nAnd dig deep trenches in thy beauty\'s field,\nThy youth\'s proud livery, so gazed on now,\nWill be a tattered weed of small worth held.\nThen being asked where all thy beauty lies,\nWhere all the treasure of thy lusty days,\nTo say within thine own deep-sunken eyes\nWere an all-eating shame and thriftless praise.\nHow much more praise deserved thy beauty\'s use\nIf thou couldst answer "This fair child of mine\nShall sum my count and make my old excuse,"\nProving his beauty by succession thine.\n  This were to be new made when thou art old\n  And see thy blood warm when thou feel\'st it cold.',
  array([0.01798188, 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ], dtype=float32)),
 (5,
  "Those hours that with gentle work did frame\nThe lovely gaze where every eye doth dwell\nWill play the tyrants to the very same\nAnd that unfair which fairly doth excel;\nFor never-resting time leads summer on\nTo hideous wint

# Extract main keywords

In [248]:
import numpy as np

In [249]:
def extract_main_keywords(group, n=10):
    entries = classified[group]
    vec_list = [x[2] for x in entries]
    
    matrix = np.array(vec_list)
    
    return matrix

In [250]:
extract_main_keywords(0)

array([[0.01798188, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01869629, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0204087 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.02120545, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02177949, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [251]:
def extract_main_keywords(group, n=10):
    entries = classified[group]
    vec_list = [x[2] for x in entries]
    
    matrix = np.array(vec_list)
    score_sum = np.sum(matrix, axis=0)
    
    paired = [(x, i) for i, x in enumerate(score_sum)]
    paired.sort(reverse=True)
    
    top = paired[:n]
    top = [x[1] for x in top ]
    
    keywords = [lexicon[x] for x in top]
    
    return keywords

In [252]:
extract_main_keywords(0)

['beauti',
 'youth',
 'fair',
 'made',
 'child',
 'make',
 'live',
 'play',
 'deep',
 'art']

In [253]:
main_keywords = defaultdict(list)

In [254]:
for group in range(len(classified)):
    main_keywords[group] = extract_main_keywords(group)
    
    print(f'* Group {group}')
    print(main_keywords[group])
    print()

* Group 0
['beauti', 'youth', 'fair', 'made', 'child', 'make', 'live', 'play', 'deep', 'art']

* Group 1
['would', 'dead', 'live', 'show', 'mine', 'eye', 'new', 'dear', 'may', 'part']

* Group 2
['kind', 'will', 'pleasur', 'wealth', 'though', 'blood', 'good', 'confess', 'frailti', 'better']

* Group 3
['old', 'present', 'best', 'strang', 'time', 'sight', 'chang', 'ever', 'date', 'shall']

* Group 4
['grief', 'cross', 'cloud', 'yet', 'sorrow', 'hath', 'rich', 'hide', 'disgrac', 'hast']

* Group 5
['better', 'speak', 'know', 'cheek', 'pain', 'heart', 'art', 'yet', 'lend', 'whilst']

